footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 4.0
transform_tolerance: 0.5

resolution: 0.05


#layer definitions
static_layer:
    map_topic: /map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser camera
    laser: {
        data_type: LaserScan, 
        clearing: true, 
        marking: true, 
        topic: scan, 
        inf_is_valid: true,
        obstacle_range: 5.5,
        raytrace_range: 6.0
        }
    camera: {
        data_type: PointCloud2,
        clearing: true, 
        marking: true, 
        topic: /camera/depth/points, 
        inf_is_valid: true, 
        min_obstacle_height: 0.05,
        obstacle_range: 5.5,
        raytrace_range: 6.0}

inflation_layer:
    inflation_radius: 1.0
