map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

frequency: 30
publish_tf: false
print_diagnostics: true
two_d_mode: true

pose0: /slam/map/pose
pose0_config: [true,  true,  true,
              true, true, true,
              true,  false, false,
              false, false, true,
              false, false, false]
pose0_differential: false
pose0_relative: false

odom0: /odometry/gps
odom0_config: [true,  true,  false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
odom0_differential: false
odom0_queue_size: 10
odom0_nodelay: true
odom0_relative: false

use_control: false